# Generated by Django 6.0.3 on 2026-03-24 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_conversation_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conversation',
            old_name='title',
            new_name='name',
        ),
    ]
