# Generated by Django 6.0.3 on 2026-03-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_conversation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(unique=True)),
                ('title', models.CharField()),
                ('embedding_id', models.UUIDField()),
                ('scraped_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'scraped_pages',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['id']},
        ),
    ]
