# Generated by Django 6.0.3 on 2026-03-26 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_scrapedpage_alter_message_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapedpage',
            name='embedding_id',
        ),
    ]
